{{ if .Values.api.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullname" . }}-api-secret
stringData:
  {{- range $key, $val := .Values.api.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}