{{ if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.fullname" . }}-tzlink-api
  namespace: {{ include "helpers.namespace" . | quote }}
  labels: {{ include "helpers.labels.api" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
{{- include "helpers.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "helpers.api.selectorLabels" . | nindent 8 }}
    spec:
      {{ if .Values.api.serviceAccount.create}}
      serviceAccountName: {{ default .Values.api.serviceAccount.name "api-sa" }}
      {{ end }}
      containers:
        - name: tzlink-api
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          resources: 
            {{ toYaml .Values.api.resources | nindent 12 | trim }}
          envFrom:
            - configMapRef:
                name: {{ include "helpers.fullname" . }}-api-cm
            {{ if .Values.api.secret }}
            - secretRef:
                name: {{ include "helpers.fullname" . }}-api-secret
            {{ end }}
            {{ range .Values.api.additionalSecrets }}
            - secretRef:
                name: {{ . }}
            {{ end }}
          {{- if .Values.api.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.livenessProbe.path }}
              port: {{ .Values.env.API_PORT }}
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.api.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.api.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.api.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.api.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.readinessProbe.path }}
              port: {{ .Values.env.API_PORT }}
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.api.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.api.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.api.readinessProbe.successThreshold }}
          {{- end }}
      {{- if .Values.api.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.api.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
{{ end }}     

        