{{ if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.fullname" . }}-api
  namespace: {{ include "helpers.namespace" . | quote }}
  labels: {{ include "helpers.labels.api" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
{{- include "helpers.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "helpers.api.selectorLabels" . | nindent 8 }}
    spec:
      {{ if .Values.api.serviceAccount.create}}
      serviceAccountName: {{ default .Values.api.serviceAccount.name "api-sa" }}
      {{ end }}
      containers:
        - name: {{ include "helpers.fullname" . }}-api
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          resources: 
            {{ toYaml .Values.api.resources | nindent 12 | trim }}
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helpers.fullname" . }}-cm
                  key: API_URL
            - name: PROXY_TESTNET_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helpers.fullname" . }}-cm
                  key: PROXY_TESTNET_URL
            - name: FRONT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helpers.fullname" . }}-cm
                  key: FRONT_URL
            {{- range $key, $val := .Values.api.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- if .Values.api.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.livenessProbe.path }}
              port: {{ .Values.api.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
          {{- end }}
          {{- if .Values.api.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.readinessProbe.path }}
              port: {{ .Values.api.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
          {{- end }}
{{ end }}     

        