{{ range $network, $data := .Values.proxy }}
---
{{ if $data.serviceAccount.create}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "helpers.namespace" $ | quote }}
  name: {{ .serviceAccount.name | default "proxy-sa" }}-{{ $network }}
{{ end }}
{{ end }}

