{{ range $network, $data := $.Values.rpcgateway}}
---
{{ if $data.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $network }}-{{ include "helpers.fullname" $ }}-rpcgateway-cm
data:
  {{ if eq $network "testnet" }}
  RPC_GATEWAY_HOSTNAME: {{ printf "http://%s" $.Values.env.TESTNET_RPC_GATEWAY_HOSTNAME }}
  RPC_GATEWAY_LABEL: {{ $.Values.env.TESTNET_RPC_GATEWAY_LABEL }}
  RPC_GATEWAY_PORT: {{ quote $.Values.env.TESTNET_RPC_GATEWAY_PORT }}
  RPC_GATEWAY_ROOT_URL: {{ $.Values.env.TESTNET_RPC_GATEWAY_ROOT_URL }}
  ARCHIVE_NODES_URL: {{ printf "http://%s" $.Values.env.TESTNET_ARCHIVE_NODES_URL }}
  ARCHIVE_NODES_PORT: {{ quote $.Values.env.TESTNET_ARCHIVE_NODES_PORT }}
  ROLLING_NODES_URL: {{ printf "http://%s" $.Values.env.TESTNET_ROLLING_NODES_URL }}
  ROLLING_NODES_PORT: {{ quote $.Values.env.TESTNET_ROLLING_NODES_PORT}}
  DATABASE_HOSTNAME: {{ $.Values.env.DATABASE_HOSTNAME }}
  DATABASE_PORT: {{ quote $.Values.env.DATABASE_PORT }}
  DATABASE_USER: {{ $.Values.env.DATABASE_USER }}
  DATABASE_PASSWORD: {{ $.Values.env.DATABASE_PASSWORD }}
  DATABASE_NAME: {{ $.Values.env.DATABASE_NAME }}
  TEZOS_NETWORK: {{ $data.network }}
  {{ end }}
  {{ if eq $network "mainnet"}}
  RPC_GATEWAY_HOSTNAME: {{ printf "http://%s" $.Values.env.MAINNET_RPC_GATEWAY_HOSTNAME }}
  RPC_GATEWAY_LABEL: {{ $.Values.env.MAINNET_RPC_GATEWAY_LABEL }}
  RPC_GATEWAY_PORT: {{ quote $.Values.env.MAINNET_RPC_GATEWAY_PORT }}
  RPC_GATEWAY_ROOT_URL: {{ $.Values.env.MAINNET_RPC_GATEWAY_ROOT_URL }}
  ARCHIVE_NODES_URL: {{ printf "http://%s" $.Values.env.MAINNET_ARCHIVE_NODES_URL }}
  ARCHIVE_NODES_PORT: {{ quote $.Values.env.MAINNET_ARCHIVE_NODES_PORT }}
  ROLLING_NODES_URL: {{ printf "http://%s" $.Values.env.MAINNET_ROLLING_NODES_URL }}
  ROLLING_NODES_PORT: {{ quote $.Values.env.MAINNET_ROLLING_NODES_PORT}}
  DATABASE_HOSTNAME: {{ $.Values.env.DATABASE_HOSTNAME }}
  DATABASE_PORT: {{ quote $.Values.env.DATABASE_PORT }}
  DATABASE_USER: {{ $.Values.env.DATABASE_USER }}
  DATABASE_PASSWORD: {{ $.Values.env.DATABASE_PASSWORD }}
  DATABASE_NAME: {{ $.Values.env.DATABASE_NAME }}
  TEZOS_NETWORK: {{ $data.network }}
  {{ end}}
  DATABASE_HOSTNAME: "tezoslinkv2-postgresql.tezoslink-postgresql.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_USER: "tzbackendv2"
  DATABASE_PASSWORD: "Titi123v2"
  DATABASE_NAME: "tezoslink"

  WEB_HOSTNAME: "test-web-svc.tezoslink-helm-test.svc.cluster.local"
  WEB_LABEL: "TezosLink"
  WEB_PORT: "3000"
  WEB_ROOT_URL: "/"
  NODE_ENV: production

  API_HOSTNAME: "test-api-svc.tezoslink-helm-test.svc.cluster.local"
  API_LABEL: "TezosLink API"
  API_PORT: "3001"
  API_ROOT_URL: "/api"


  # Concat
  # RPC_GATEWAY_MAINNET_URL: "http://localhost:3002/rpc"
  # RPC_GATEWAY_TESTNET_URL: "http://localhost:3002/rpc"

  ARCHIVE_NODES_URL: "https://api.tez.ie/rpc/mainnet"
  ARCHIVE_NODES_PORT: "443"
  ROLLING_NODES_URL: "https://api.tez.ie/rpc/mainnet"
  ROLLING_NODES_PORT: "443"

{{ end }}
{{ end }}