{{ range $network, $data := .Values.rpcgateway }}
---
{{ if and $data.serviceAccount.create $data.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "helpers.namespace" $ | quote }}
  name: {{ $network }}-{{ .serviceAccount.name | default "rpcgateway-sa" }}
{{ end }}
{{ end }}

