{{ range $network, $data := .Values.proxy }}
---
{{ if $data.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullname" $ }}-proxy-{{ $network }}
  namespace: {{ include "helpers.namespace" $ | quote }}
data:
  {{- range $key, $val := $data.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}
{{ end}}