{{ range $network, $data := .Values.rpcgateway }}
---
{{ if $data.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $network }}-{{ include "helpers.fullname" $ }}-rpcgateway-secret
  namespace: {{ include "helpers.namespace" $ | quote }}
data:
  {{- range $key, $val := $data.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}
{{ end}}