{{ range $network, $data := .Values.rpcgateway }}
---
{{- if $data.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $network }}-{{ include "helpers.fullname" $ }}-rpcgateway-svc
  namespace: {{ include "helpers.namespace" $ | quote }}
  labels: {{ include "helpers.labels.rpcgateway" (dict "root" $ "network" $network) | nindent 4 }}
  annotations: 
    {{ toYaml $data.service.annotations | nindent 4 | trim }}
spec:
  type: {{ $data.service.type }}
{{- if $data.service.clusterIP }}
  clusterIP: {{ $data.service.clusterIP }}
{{- end }}
{{- if $data.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{- range $data.service.loadBalancerSourceRanges}}
    - {{ . | indent 4 }}
{{- end}}
{{- end }}
  {{ if eq $network "testnet" }}
  ports:
    - port:  {{ $.Values.env.TESTNET_NEXT_PUBLIC_RPC_GATEWAY_PORT}}
      name: http
      targetPort: {{ $.Values.env.TESTNET_NEXT_PUBLIC_RPC_GATEWAY_PORT}}
      {{- if eq $data.service.type "NodePort" }}
      nodePort: {{ $data.service.nodePorts.http }}
      {{- end }}
  {{ end }}
  {{ if eq $network "mainnet" }}
  ports:
    - port:  {{ $.Values.env.MAINNET_NEXT_PUBLIC_RPC_GATEWAY_PORT}}
      name: http
      targetPort: {{ $.Values.env.MAINNET_NEXT_PUBLIC_RPC_GATEWAY_PORT}}
      {{- if eq $data.service.type "NodePort" }}
      nodePort: {{ $data.service.nodePorts.http }}
      {{- end }}
  {{ end }}
  selector:
{{- include "helpers.rpcgateway.selectorLabels" (dict "root" $ "network" $network) | nindent 8 }}
{{- end }}
{{ end }}