{{ range $network, $data := .Values.proxy }}
---
{{- if $data.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.fullname" $ }}-proxy
  namespace: {{ include "helpers.namespace" $ | quote }}
  labels: {{ include "helpers.labels.proxy" $ | nindent 4 }}
  annotations: 
    {{ toYaml $data.service.annotations | nindent 4 | trim }}
spec:
  type: {{ $data.service.type }}
{{- if $data.service.clusterIP }}
  clusterIP: {{ $data.service.clusterIP }}
{{- end }}
{{- if $data.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{- range $data.service.loadBalancerSourceRanges}}
    - {{ . | indent 4 }}
{{- end}}
{{- end }}
  ports:
    - port:  {{ $data.service.ports.http }}
      name: http
      targetPort: {{ $data.service.ports.http }}
{{- if eq $data.service.type "NodePort" }}
      nodePort: {{ $data.service.nodePorts.http }}
{{- end }}
  selector:
{{- include "helpers.proxy.selectorLabels" . | nindent 8 }}
{{- end }}
{{ end }}