apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.fullname" . }}-front
  namespace: {{ include "helpers.namespace" . | quote }}
  labels: {{ include "helpers.labels.front" . | nindent 4 }}
spec:
  replicas: {{ .Values.front.replicas }}
  selector:
    matchLabels:
{{- include "helpers.front.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "helpers.front.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: docker-pull-secret
      containers:
      - name: {{ include "helpers.fullname" . }}-front
        imagePullPolicy: {{ .Values.front.image.pullPolicy }}
        image: "{{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}"
        resources:
{{toYaml .Values.front.resources | indent 10}}
        env:
{{toYaml .Values.front.env | indent 10}}