version: 2.1

orbs: 
  path-filtering: circleci/path-filtering@0.1.3
    
setup: true 

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          filters:
            branches:
              only: 
                - main
                - devops/helm-chart
          base-revision: <<pipeline.git.branch>>
          config-path: .circleci/workflows.yml
          mapping: |
            helm-charts/.* charts true
