version: 2.1

orbs: 
  path-filtering: circleci/path-filtering@0.1.3
    
setup: true 

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          filters:
            branches:
              only:
                - application-segmentation-2
                - staging 
                - main
                - preprod
          base-revision: <<pipeline.git.branch>>
          config-path: .circleci/workflows.yml
          mapping: |
            app/.* app true
            devops/.* devops true
            .gitleaksignore app true
            .gitleaksignore devops true