basePath: /api/v1
definitions:
  inputs.NewProject:
    properties:
      title:
        type: string
    type: object
  model.Health:
    properties:
      connectedToDb:
        type: boolean
    type: object
  outputs.MetricsOutput:
    properties:
      requestsCount:
        type: integer
    type: object
  outputs.ProjectOutputWithMetrics:
    properties:
      metrics:
        $ref: '#/definitions/outputs.MetricsOutput'
        type: object
      title:
        type: string
      uuid:
        type: string
    type: object
info:
  contact:
    email: email@ded.fr
    name: API Support
  description: API to manage projects
  license: {}
  title: Tezos Link API
  version: v1
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Health'
      summary: get application health
  /projects:
    post:
      parameters:
      - description: New Project
        in: body
        name: new-project
        required: true
        schema:
          $ref: '#/definitions/inputs.NewProject'
          type: object
      produces:
      - application/json
      responses:
        "201": {}
        "400": {}
      summary: Create a Project
  /projects/{uuid}:
    get:
      parameters:
      - description: Project UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/outputs.ProjectOutputWithMetrics'
      summary: Get a Project with the associated metrics
swagger: "2.0"
