# Install dependencies only when needed
FROM node:19-alpine AS deps

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:19-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN yarn build

# Production image, copy all the files and run next
FROM node:19-alpine AS production

WORKDIR /app

RUN adduser -D nextjs --uid 10000 && chown -R nextjs /app

COPY --from=builder --chown=nextjs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs /app/public ./public
COPY --from=builder --chown=nextjs /app/src ./src
COPY --from=builder --chown=nextjs /app/.next ./.next

COPY --from=builder --chown=nextjs /app/package.json ./package.json
COPY --from=builder --chown=nextjs /app/next.config.js ./next.config.js
COPY --from=builder --chown=nextjs /app/tsconfig.json ./tsconfig.json

USER nextjs

CMD ["yarn", "start"]