version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: tezoslink
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: build/package/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENV: local
    restart: on-failure
    depends_on:
      - postgres
  proxy:
    build:
      context: .
      dockerfile: build/package/proxy.Dockerfile
    ports:
      - "8001:8001"
    environment:
      ENV: local
      TEZOS_NETWORK: MAINNET
    restart: on-failure
    depends_on:
      - postgres
  proxy-carthagenet:
    build:
      context: .
      dockerfile: build/package/proxy.Dockerfile
    ports:
      - "8002:8002"
    environment:
      ENV: local
      TEZOS_NETWORK: CARTHAGENET
      SERVER_PORT: 8002
    restart: on-failure
    depends_on:
      - postgres
  node:
    image: mockserver/mockserver:mockserver-5.9.0
    environment:
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 1090
    ports:
      - "8765:1090"
  node-rolling:
    image: mockserver/mockserver:mockserver-5.9.0
    environment:
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 1090
    ports:
      - "8766:1090"