apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.fullname" .}}-web-cm
data:
  {{ if .Values.env.API_PORT}}
  NEXT_PUBLIC_API_URL: {{ printf "http://%s:%v%s" .Values.env.API_HOSTNAME .Values.env.API_PORT .Values.env.API_ROOT_URL}}
  {{ else }}
  NEXT_PUBLIC_API_URL: {{ printf "http://%s%s" .Values.env.API_HOSTNAME .Values.env.API_ROOT_URL}}  
  {{ end }}

  {{ if .Values.env.MAINNET_RPC_GATEWAY_PORT}}
  NEXT_PUBLIC_RPC_GATEWAY_MAINNET_URL: {{ printf "http://%s:%v%s" .Values.env.MAINNET_RPC_GATEWAY_HOSTNAME .Values.env.MAINNET_RPC_GATEWAY_PORT .Values.env.MAINNET_RPC_GATEWAY_ROOT_URL}}
  {{ else }}
  NEXT_PUBLIC_RPC_GATEWAY_MAINNET_URL: {{ printf "http://%s%s" .Values.env.MAINNET_RPC_GATEWAY_HOSTNAME .Values.env.MAINNET_RPC_GATEWAY_ROOT_URL}}
  {{ end }}

  {{ if .Values.env.TESTNET_RPC_GATEWAY_PORT}}
  NEXT_PUBLIC_RPC_GATEWAY_TESTNET_URL: {{ printf "http://%s:%v%s" .Values.env.TESTNET_RPC_GATEWAY_HOSTNAME .Values.env.TESTNET_RPC_GATEWAY_PORT .Values.env.TESTNET_RPC_GATEWAY_ROOT_URL}}
  {{ else}}
  NEXT_PUBLIC_RPC_GATEWAY_TESTNET_URL: {{ printf "http://%s%s" .Values.env.TESTNET_RPC_GATEWAY_HOSTNAME .Values.env.TESTNET_RPC_GATEWAY_ROOT_URL}}
  {{ end }}
