apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.fullname" .}}-web-cm
data:

  NEXT_PUBLIC_API_URL: {{ printf "https://%s%s" .Values.env.API_HOSTNAME .Values.env.API_ROOT_URL}}  
  NEXT_PUBLIC_RPC_GATEWAY_MAINNET_URL: {{ printf "https://%s%s" .Values.env.MAINNET_RPC_GATEWAY_HOSTNAME .Values.env.MAINNET_RPC_GATEWAY_ROOT_URL}}
  NEXT_PUBLIC_RPC_GATEWAY_TESTNET_URL: {{ printf "https://%s%s" .Values.env.TESTNET_RPC_GATEWAY_HOSTNAME .Values.env.TESTNET_RPC_GATEWAY_ROOT_URL}}

