{{ if .Values.web.serviceAccount.create}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "helpers.namespace" . | quote }}
  name: {{ .Values.web.serviceAccount.name | default "web-sa" }}
{{ end }}

