{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.fullname" . }}
  namespace: {{ include "helpers.namespace" . | quote }}
  labels: {{- include "helpers.labels.proxy" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  clusterIP: {{ .Values.proxy.service.clusterIP }}
  {{- if .Values.proxy.service.sessionAffinity }}
  sessionAffinity: {{ .Values.proxy.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.proxy.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.proxy.service.type "LoadBalancer") (eq .Values.proxy.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.proxy.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") (not (empty .Values.proxy.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.proxy.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") (not (empty .Values.proxy.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") (eq .Values.proxy.service.externalTrafficPolicy "Local") .Values.proxy.service.healthCheckNodePort }}
  healthCheckNodePort: {{ .Values.proxy.service.healthCheckNodePort }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.proxy.service.ports.http }}
      targetPort: 3000
      {{- if and .Values.proxy.service.nodePorts.http (or (eq .Values.proxy.service.type "NodePort") (eq .Values.proxy.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.proxy.service.nodePorts.http }}
      {{- end }}
    {{- if .Values.proxy.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.proxy.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector:
    {{- include "helpers.selectorLabels" . | nindent 6 }}
{{- end }}
