{{ if .Values.cron.secret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "helpers.namespace" . | quote }}
  name: {{ include "helpers.fullname" . }}-cron-secret
stringData:
  {{- range $key, $val := .Values.cron.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}